utils/docker-ce: sync with openwrt, 2020.11

diff --git a/utils/docker-ce/files/dockerd.init b/utils/docker-ce/files/dockerd.init
--- a/utils/docker-ce/files/dockerd.init
+++ b/utils/docker-ce/files/dockerd.init
@@ -3,19 +3,18 @@
 USE_PROCD=1
 START=25
 
-EXTRA_COMMANDS="uciadd ucidel"
-EXTRA_HELP="\
-	uciadd  Add default bridge configuration to network and firewall uci config
-	ucidel  Delete default bridge configuration from network and firewall uci config"
+extra_command "uciadd" "<interface> <device> <zone> Add docker bridge configuration to network and firewall uci config"
+extra_command "ucidel" "<interface> <device> <zone> Delete docker bridge configuration from network and firewall uci config"
 
-DOCKERD_CONF="/tmp/dockerd/daemon.json"
+DOCKER_CONF_DIR="/tmp/dockerd"
+DOCKERD_CONF="${DOCKER_CONF_DIR}/daemon.json"
 
 uci_quiet() {
-	uci -q ${@} >/dev/null
+	uci -q "${@}" >/dev/null
 }
 
 json_add_array_string() {
-	json_add_string "" "$1"
+	json_add_string "" "${1}"
 }
 
 boot() {
@@ -23,67 +22,54 @@ boot() {
 	rc_procd start_service
 }
 
-uciupdate() {
-	local net="$1"
-
-	uci -q get network.docker >/dev/null || {
-		logger -t "dockerd-init" -p warn "No network uci config section for docker default bridge (docker0) found"
-		return
-	}
-
-	[ -z "$net" ] && {
-		logger -t "dockerd-init" -p notice "Removing network uci config options for docker default bridge (docker0)"
-		uci_quiet delete network.docker.netmask
-		uci_quiet delete network.docker.ipaddr
-		uci_quiet commit network
-		return
-	}
-
-	eval "$(ipcalc.sh "$net")"
-	logger -t "dockerd-init" -p notice "Updating network uci config option \"$net\" for docker default bridge (docker0)"
-	uci_quiet set network.docker.netmask="$NETMASK"
-	uci_quiet set network.docker.ipaddr="$IP"
-	uci_quiet commit network
-}
-
 uciadd() {
+	local iface="$1"
+	local device="$2"
+	local zone="$3"
+
+	[ -z "$iface" ] && {
+		iface="docker"
+		device="docker0"
+		zone="docker"
+	}
+
 	/etc/init.d/dockerd running && {
 		echo "Please stop dockerd service first"
 		exit 0
 	}
 
 	# Add network interface
-	if ! uci -q get network.docker >/dev/null; then
-		logger -t "dockerd-init" -p notice "Adding docker default interface to network uci config (docker)"
+	if ! uci_quiet get network.${iface}; then
+		logger -t "dockerd-init" -p notice "Adding docker default interface to network uci config (${iface})"
 		uci_quiet add network interface
-		uci_quiet rename network.@interface[-1]="docker"
-		uci_quiet set network.docker.ifname="docker0"
-		uci_quiet set network.docker.proto="static"
-		uci_quiet set network.docker.auto="0"
+		uci_quiet rename network.@interface[-1]="${iface}"
+		uci_quiet set network.@interface[-1].ifname="${device}"
+		uci_quiet set network.@interface[-1].proto="none"
+		uci_quiet set network.@interface[-1].auto="0"
 		uci_quiet commit network
 	fi
 
 	# Add docker bridge device
-	if ! uci -q get network.docker0 >/dev/null; then
-		logger -t "dockerd-init" -p notice "Adding docker default bridge device to network uci config (docker0)"
+	if ! uci_quiet get network.${device}; then
+		logger -t "dockerd-init" -p notice "Adding docker default bridge device to network uci config (${device})"
 		uci_quiet add network device
-		uci_quiet rename network.@device[-1]="docker0"
-		uci_quiet set network.docker0.type="bridge"
-		uci_quiet set network.docker0.name="docker0"
-		uci_quiet add_list network.docker0.ifname="docker0"
+		uci_quiet rename network.@device[-1]="${device}"
+		uci_quiet set network.@device[-1].type="bridge"
+		uci_quiet set network.@device[-1].name="${device}"
+		uci_quiet add_list network.@device[-1].ifname="${device}"
 		uci_quiet commit network
 	fi
 
 	# Add firewall zone
-	if ! uci -q get firewall.docker >/dev/null; then
-		logger -t "dockerd-init" -p notice "Adding docker default firewall zone to firewall uci config (docker)"
+	if ! uci_quiet get firewall.${zone}; then
+		logger -t "dockerd-init" -p notice "Adding docker default firewall zone to firewall uci config (${zone})"
 		uci_quiet add firewall zone
-		uci_quiet rename firewall.@zone[-1]="docker"
-		uci_quiet set firewall.docker.network="docker"
-		uci_quiet set firewall.docker.input="REJECT"
-		uci_quiet set firewall.docker.output="ACCEPT"
-		uci_quiet set firewall.docker.forward="REJECT"
-		uci_quiet set firewall.docker.name="docker"
+		uci_quiet rename firewall.@zone[-1]="${zone}"
+		uci_quiet set firewall.@zone[-1].network="${iface}"
+		uci_quiet set firewall.@zone[-1].input="REJECT"
+		uci_quiet set firewall.@zone[-1].output="ACCEPT"
+		uci_quiet set firewall.@zone[-1].forward="REJECT"
+		uci_quiet set firewall.@zone[-1].name="${zone}"
 		uci_quiet commit firewall
 	fi
 
@@ -91,30 +77,44 @@ uciadd() {
 }
 
 ucidel() {
+	local iface="$1"
+	local device="$2"
+	local zone="$3"
+
+	[ -z "$iface" ] && {
+		iface="docker"
+		device="docker0"
+		zone="docker"
+	}
+
 	/etc/init.d/dockerd running && {
 		echo "Please stop dockerd service first"
 		exit 0
 	}
 
-	logger -t "dockerd-init" -p notice "Deleting docker default bridge device from network uci config (docker0)"
-	uci_quiet delete network.docker0
-	uci_quiet commit network
+	if uci_quiet get network.${device}; then
+		logger -t "dockerd-init" -p notice "Deleting docker default bridge device from network uci config (${device})"
+		uci_quiet delete network.${device}
+		uci_quiet commit network
+	fi
 
-	logger -t "dockerd-init" -p notice "Deleting docker default interface from network uci config (docker)"
-	uci_quiet delete network.docker
-	uci_quiet commit network
+	if uci_quiet get network.${iface}; then
+		logger -t "dockerd-init" -p notice "Deleting docker default interface from network uci config (${iface})"
+		uci_quiet delete network.${iface}
+		uci_quiet commit network
+	fi
 
-	logger -t "dockerd-init" -p notice "Deleting docker firewall zone from firewall uci config (docker)"
-	uci_quiet delete firewall.docker
-	uci_quiet commit firewall
+	if uci_quiet get firewall.${zone}; then
+		logger -t "dockerd-init" -p notice "Deleting docker firewall zone from firewall uci config (${zone})"
+		uci_quiet delete firewall.${zone}
+		uci_quiet commit firewall
+	fi
 
 	reload_config
 }
 
 process_config() {
-	local alt_config_file data_root log_level bip
-
-	rm -f "$DOCKERD_CONF"
+	local alt_config_file data_root log_level iptables bip
 
 	[ -f /etc/config/dockerd ] || {
 		# Use the daemon default configuration
@@ -122,23 +122,27 @@ process_config() {
 		return 0
 	}
 
-	config_load 'dockerd'
+	# reset configuration
+	rm -fr "${DOCKER_CONF_DIR}"
+	mkdir -p "${DOCKER_CONF_DIR}"
 
+	config_load 'dockerd'
 	config_get alt_config_file globals alt_config_file
-	[ -n "$alt_config_file" ] && [ -f "$alt_config_file" ] && {
-		ln -s "$alt_config_file" "$DOCKERD_CONF"
+	[ -n "${alt_config_file}" ] && [ -f "${alt_config_file}" ] && {
+		ln -s "${alt_config_file}" "${DOCKERD_CONF}"
 		return 0
 	}
 
 	config_get data_root globals data_root "/opt/docker/"
 	config_get log_level globals log_level "warn"
+	config_get_bool iptables globals iptables "1"
 	config_get bip globals bip ""
 
 	. /usr/share/libubox/jshn.sh
 	json_init
-	json_add_string "data-root" "$data_root"
-	json_add_string "log-level" "$log_level"
-	[ -z "$bip" ] || json_add_string "bip" "$bip"
+	json_add_string "data-root" "${data_root}"
+	json_add_string "log-level" "${log_level}"
+	[ -z "${bip}" ] || json_add_string "bip" "${bip}"
 	json_add_array "registry-mirrors"
 	config_list_foreach globals registry_mirrors json_add_array_string
 	json_close_array
@@ -146,10 +150,10 @@ process_config() {
 	config_list_foreach globals hosts json_add_array_string
 	json_close_array
 
-	mkdir -p /tmp/dockerd
-	json_dump > "$DOCKERD_CONF"
+	json_add_boolean iptables "${iptables}"
+	[ "${iptables}" -ne "0" ] && config_foreach iptables_add_blocking_rule firewall
 
-	uciupdate "$bip"
+	json_dump > "${DOCKERD_CONF}"
 }
 
 start_service() {
@@ -159,10 +163,10 @@ start_service() {
 
 	procd_open_instance
 	procd_set_param stderr 1
-	if [ -z "$DOCKERD_CONF" ]; then
+	if [ -z "${DOCKERD_CONF}" ]; then
 		procd_set_param command /usr/bin/dockerd
 	else
-		procd_set_param command /usr/bin/dockerd --config-file="$DOCKERD_CONF"
+		procd_set_param command /usr/bin/dockerd --config-file="${DOCKERD_CONF}"
 	fi
 	procd_set_param limits nofile="${nofile} ${nofile}"
 	procd_close_instance
@@ -177,44 +181,43 @@ service_triggers() {
 	procd_add_reload_trigger 'dockerd'
 }
 
-ip4tables_remove_nat() {
-	iptables -t nat -D OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-	iptables -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
+iptables_add_blocking_rule() {
+	local cfg="$1"
 
-	iptables -t nat -F DOCKER
-	iptables -t nat -X DOCKER
-}
+	local device=""
 
-ip4tables_remove_filter() {
-	# Chain DOCKER-USER is only present,
-	# if bip option is NOT set, so >/dev/null 2>&1
-	iptables -t filter -D FORWARD -j DOCKER-USER >/dev/null 2>&1
-	iptables -t filter -D FORWARD -j DOCKER-ISOLATION-STAGE-1
-	iptables -t filter -D FORWARD -o docker0 -j DOCKER
+	handle_iptables_rule() {
+		local interface="$1"
+		local outbound="$2"
 
-	iptables -t filter -F DOCKER
-	iptables -t filter -F DOCKER-ISOLATION-STAGE-1
-	iptables -t filter -F DOCKER-ISOLATION-STAGE-2
-	# Chain DOCKER-USER is only present,
-	# if bip option is NOT set, so >/dev/null 2>&1
-	iptables -t filter -F DOCKER-USER >/dev/null 2>&1
+		local inbound=""
 
-	iptables -t filter -X DOCKER
-	iptables -t filter -X DOCKER-ISOLATION-STAGE-1
-	iptables -t filter -X DOCKER-ISOLATION-STAGE-2
-	# Chain DOCKER-USER is only present,
-	# if bip option is NOT set, so >/dev/null 2>&1
-	iptables -t filter -X DOCKER-USER >/dev/null 2>&1
-}
+		. /lib/functions/network.sh
+		network_get_physdev inbound "${interface}"
 
-ip4tables_remove() {
-	ip4tables_remove_nat
-	ip4tables_remove_filter
+		[ -z "$inbound" ] && {
+			logger -t "dockerd-init" -p notice "Unable to get physical device for interface ${interface}"
+			return
+		}
+
+		if ! iptables --table filter --check DOCKER-USER --in-interface "${inbound}" --out-interface "${outbound}" --jump DROP 2>/dev/null; then
+			logger -t "dockerd-init" -p notice "Drop traffic from ${inbound} to ${outbound}"
+			iptables --table filter --insert DOCKER-USER --in-interface "${inbound}" --out-interface "${outbound}" --jump DROP
+		fi
+	}
+
+	config_get device "$cfg" device
+
+	[ -z "$device" ] && {
+		logger -t "dockerd-init" -p notice "No device configured for ${cfg}"
+		return
+	}
+
+	config_list_foreach "$cfg" blocked_interfaces handle_iptables_rule "$device"
 }
 
 stop_service() {
 	if /etc/init.d/dockerd running; then
 		service_stop "/usr/bin/dockerd"
-		ip4tables_remove
 	fi
 }
